### ISSUE TITLE
Verify Behavior before deprecating iron-router-autoscroll

### ISSUE THREAD

**Issue by deanrad** [okgrow/router-autoscroll#12]
Verify behavior
- [ ] http://flow-router-autoscroll.meteor.com/
- [ ] http://iron-router-autoscroll.meteor.com/

https://trello.com/c/TMcyn9HN/565-migrate-iron-router-autoscroll-to-router-autoscroll

**Comment by ghost** [comment]
Router-autoscroll is also being deprecated as of now.
