### ISSUE TITLE
Autscroll not working on smaller devices

### ISSUE THREAD

**Issue by jayspirits** [okgrow/router-autoscroll#16]
I have tried testing it on some smartphones and auto scroll ddnt work. I also tried testing it on a regular tablet device, also didnt work on portrait orientation but somehow works if landscaped. I thought it was a device issue but out of it i tried testing it on a desktop web browser and adjusted the window size as small as a regular smartphone then i replicated the problem.

**Comment by deanrad** [comment]
Thanks for leaving this issue. Can you narrow down to what actions you take are not working, and for which browsers?  The following example sties have several links (between documents no hashtag, same documents, no hashtag), and if you can narrow down a reproducible scenario (action, browser combo) for us I'd really appreciate it !
- http://iron-router-autoscroll.meteor.com
- http://flow-router-autoscroll.meteor.com

**Comment by jayspirits** [comment]
What i did is that i have this rows of boxed items that doesnt fit on a page so i have to scroll down the page to see the other items below. The box has an onclick event that routes to the full details of the clicked item. On that page theres a back button that links back to the previous route. Initialy when i press back the page doesnt scroll down to where it was before.So i applied router-autoscroll and somehow solved the issue. But when i tried testing it on phones it didnt work. Test it on tablets works only if lanscaped. I thought it was a browser issue but tried it on desktop both on firefox and chrome and adjusted the window size as small as a regular smartphone then i somehow replicated the problem.
So im guessing theres a limitation on screen dimension. I believe im not using hashtags.

I used iron-router for my routes. Test it on chrome browsers on phone. On app its chromium33.

P.S. I accidentally pressed the close and comment button . :)

**Comment by jayspirits** [comment]
So i applied router-autoscroll and somehow solved the issue. But when i tried testing it on phones it didnt work. Test it on tablets works only if lanscaped. I thought it was a browser issue but tried it on desktop both on firefox and chrome and adjusted the window size as small as a regular smartphone then i somehow replicated the problem.
So im guessing theres a limitation on screen dimension. I believe im not using hashtags.

I used iron-router for my routes. Test it on chrome browsers on phone. On app its chromium33.

P.S. I accidentally pressed the close and comment button . :)

**Comment by phocks** [comment]
This seems to be the same issue I was having on the old iron-router-autoscroll where when I browse on my iPhone Safari and Chrome, the auto scroll doesn't work. Probably those mobile browsers handle scrolling differently....

**Comment by ghost** [comment]
Hello all, at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
