### ISSUE TITLE
Get rid of jquery

### ISSUE THREAD

**Issue by andrejsm** [okgrow/router-autoscroll#19]
As of Meteor 1.2 jquery is removable. If it's done, your package throws an error as it has dependency on jquery. Sadly it is not defined as requirement in package.

I suggest to remove jquery at all. No need to load bulky lib for simple tasks easily achievable without it.

**Comment by pauldowman** [comment]
I'd be happy to accept a PR for this. jQuery is used in a few places [in this file](https://github.com/okgrow/router-autoscroll/blob/master/client/router-autoscroll.js). Mainly for $.animate, which could be optional I guess.

**Comment by pauldowman** [comment]
I mean a PR for removing jQuery. We should probably add it as a dependency in the meantime.
