### ISSUE TITLE
TypeError: Cannot set property 'animationDuration' of undefined

### ISSUE THREAD

**Issue by fabyeah** [okgrow/router-autoscroll#20]
I want to override the animation duration with

```
RouterAutoscroll.animationDuration = 0;
```

but then I get the build error 

```
TypeError: Cannot set property 'animationDuration' of undefined
```

Though I can set `RouterAutoscroll.animationDuration` manually later, but it's not defined when the page first loads.

Is this the expected behavior? Do I have to keep checking if it's defined with setInterval?

I'm using version 0.0.10 as I haven't upgraded to Meteor 1.2 yet, because of bugs with different packages.

**Comment by fabyeah** [comment]
I updated to 0.1.0, error is still occurring.

**Comment by pauldowman** [comment]
Thanks, we'll take a look as soon as we can.

**Comment by fabyeah** [comment]
I'm on Meteor 1.2 now, error still occures. I maintain an all-package structure like telescope. I api.use and api.imply the okgrow:router-autoscroll package in my lib package, then set RouterAutoscroll.animationDuration in my core package. 

If I wrap it in Meteor.setTimeout, there is no error.

**Comment by karldanninger** [comment]
hey @fabyeah, I'm taking a look at this. Is your package public? I'm having trouble reproducing this

**Comment by fabyeah** [comment]
@kdanninger unfortunately not, I'll see if I can recreate the issue in a public project.

**Comment by karldanninger** [comment]
Ok thanks! @fabyeah; Looking forward to a repro.

What I've done so far diagnosing this issue:
- I cloned latest [Telescope](https://github.com/TelescopeJS/Telescope) Meteor version 1.2.0.2

_telescope-lib package includes okgrow:router-autoscroll already_
- Set animationDuration in a Meteor.startup() in a lib folder within telescope-lib package
- confirm that animationDuration has been set

**Comment by fabyeah** [comment]
@kdanninger oh god, I put it in a shared directory... because iron-router tells you to put your routes there. 

Thanks for following up!

Closed.

**Comment by karldanninger** [comment]
Awesome! Glad you found it :+1:
