### ISSUE TITLE
Auto scroll to previous scroll position is not working when we click back button.

### ISSUE THREAD

**Issue by kobescoresagain** [okgrow/router-autoscroll#22]
I have complex routes in my meteor project with iron router instead of simple route configuration 

Example :
1)Router.route(Home + '/category/:categoryVariable', )
2)Router.route(Home + '/category/division', )

My requirement :

If i am  on the route /category/:categoryVariable,clicking on any link on the page would open a new route/page . Clicking back button should restore scroll position in /category/:categoryVariable page.

I have installed package okgrow:router-autoscroll . The packages is not helping me restore scroll position after user clicks browser  back button. 

It works if i am on home page which has simple route( Router.route(Home) and not working for complex routes. 

Any suggestions on how to get this package working? 

Thanks!

**Comment by JWPapi** [comment]
Same  as #44

**Comment by ghost** [comment]
Hello all, at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
