### ISSUE TITLE
Add acceptance testing to verify behavior

### ISSUE THREAD

**Issue by benthemonkey** [okgrow/router-autoscroll#26]
I was thinking about making some automated tests to verify that autoscrolling works in an expected, consistent way across the examples.

Do you have any preferred tools? If not I was going to use Nightwatch + Mocha.

**Comment by pauldowman** [comment]
That would be amazing! ❤️❤️😀 This has been on our list forever and is obviously farther down than it should be.  

I'm fine with Nightwatch + Mocha if that's your preferred end to end testing setup. I assume you'd be testing against the example apps in this repo. 

And wow, thanks!
