### ISSUE TITLE
Autoscroll not working at all with Iron Router

### ISSUE THREAD

**Issue by ghost** [okgrow/router-autoscroll#28]
I cannot get any command, any package, or this package, to allow me to scroll to the top. Even through the console. Any ideas?

**Comment by zulhfreelancer** [comment]
Same here. Doesn't work.

**Comment by karldanninger** [comment]
I just tried it, seems to work with Meteor 1.2.1 and the latest iron:router. Are there any errors? What versions are you using?

**Comment by karldanninger** [comment]
@chriskgregory @zulhfreelancer I just tested again with a couple simple apps, it seems to work just fine. I'm closing this issue for now.

If you could please include a sample app reproduction, feel free to reopen this issue, and I'll be glad to help solve it!
