### ISSUE TITLE
Utilize Scroll Restoration API where available

### ISSUE THREAD

**Issue by deanrad** [okgrow/router-autoscroll#3]
Per https://github.com/NicolasParada
There is a new history.scrollRestoration API:
https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration --Specs here
Check it :)

**Comment by deanius** [comment]
That appears to be out of scope for our current purpose. However we will carefully review this further if you submit a Pull Request demonstrating the problem, sketching in as much of a solution as you feel you comfortable.

**Comment by ghost** [comment]
Hi @deanius unfortunately, we will no longer be dedicating resources to the development of router-autoscroll. We are using react-router which has auto scroll functionality, so this package will be deprecated. Feel free to fork it and support it.
