### ISSUE TITLE
Define route exceptions

### ISSUE THREAD

**Issue by fabyeah** [okgrow/router-autoscroll#31]
I have a chat inside my app. I want the page to scroll to the bottom when opening the chat route, because like in most chat apps, messages are ordered chronologically with the new ones at the bottom. It would be nice if I could define an exception for this route, so autoscroll doesn't execute. How do I work around this issue? I tried scrolling down on `onRendered`, but I would need some arbitrary `Meteor.setTimeout` for it to run after autoscroll. 

Im using FlowRouter.

**Comment by pauldowman** [comment]
Does the `maintainScroll=1` parameter do what you're looking for? Details [here](https://github.com/okgrow/router-autoscroll#configuration)

**Comment by fabyeah** [comment]
I don't think it's possible to set a hash in FlowRouter...?

I tried entering a URL manually with appended "#maintainScroll=1". Would that work? Doesn't seem to prevent the scrolling to the top.

**Comment by nickgeerts** [comment]
I have the same problem. I think this [this pull request](https://github.com/okgrow/router-autoscroll/pull/15) would fix it, but it was not accepted. Basically, I think it's better to control the maintainScroll with query params in FlowRouter. FlowRouter doesn't seem to like the hash. Is there any reason not to accept that pull request?

**Comment by fabyeah** [comment]
@pauldowman Step 9 in the flow-router example does not maintain scroll position for me. Does it work for you?

**Comment by tcastelli** [comment]
+1

**Comment by ghost** [comment]
Hello all, at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.

**Comment by tomyo** [comment]
Hi everyone, I needed this feature, so I forked this project and implement it. The problem is I had to change the main API, so I ended up rewriting everything and making a new package, just for flow router.
If you use flow router and want this feature, give it a try:
https://github.com/tomyo/flow-router-autoscroll

**Comment by tomyo** [comment]
Oh, the way I implement it was using the `except` option when defining triggers in `flow router`, wich excludes the trigger from certain routes. The API change, is that now you have to call `init()` to apply the triggers with the routes to exclude you provided.
