### ISSUE TITLE
[Fix] maintainScroll=1 Problem

### ISSUE THREAD

**Issue by tcastelli** [okgrow/router-autoscroll#34]
I had problems using the maintainScroll=1 in any kind of route since it still went to the top of the page.
I've found a quick fix just in case anybody wants to plug it in 

``` js
var scheduleScroll = function () {
    Tracker.afterFlush(function () {
        Meteor.defer(function () {
            var position = getScrollToPosition();
            if (position !== undefined)
                scrollTo(position);
        });
    });
};
```

**Comment by karldanninger** [comment]
Okay, we will look into this!

**Comment by tcastelli** [comment]
Any chance to include this fix on the package?
As I could see, when maintainScroll is on, getScrollToPosition() returns undefined, and calling scrollTo(undefined) doesn't make a lot of sense to me.
Furthermore,  In scrollTo function, the new position will be calculated by doing undefined - RouterAutoscroll.marginTop which is wrong by definition in my opinion.
Cheers

**Comment by ghost** [comment]
Hi @tcastelli, we will no longer be dedicating the time into maintaining this package. At OK GROW we are using react-router so this will no longer be used in our future projects.
