### ISSUE TITLE
Anchor links with dots don't work

### ISSUE THREAD

**Issue by BeSports** [okgrow/router-autoscroll#35]
Just a small little error I noticed, whenever you have a link that points to an anchor that contains a dot (.), it will not work. It will scroll down to the correct position, but will immediately scroll back up again.

E.g.

`<a href="#3.-general" title="3. General">3. General</a>`

`<h2 className="ui blue header" id="3.-general"><a name="3.-general" href="#3.-general"></a>3. General</h2>`

**Comment by karldanninger** [comment]
@BeSports confirmed that this is in fact a bug! Good catch
