### ISSUE TITLE
Need to readjust scrollTop after changing element height

### ISSUE THREAD

**Issue by mrgiba** [okgrow/router-autoscroll#37]
Sometimes, a programatic change on the height of a page element (in my case, a child of body element) causes the whole page to scroll down
To overcome that, I wonder if router-autoscroll could store the latest scrollTop value applied to the page and make that public, so that, after the height change, I could have code gathering that scrollTop value and reapplying that to the page
The concern is specific to Chrome. Not sure whether there's an approach to prevent the unwanted scrolling

I can code a PR for that

Thanks

**Comment by karldanninger** [comment]
Hey! I'm a little confused by the use case. Could you give an example?

**Comment by mrgiba** [comment]
I am working on application having animations on the transition of pages

I am not aware of the specifics of Chrome (I am using version 48.0.2564.116). 
The navigation scenario is: 
pageA --- [user click] ---> pageB --- [browser back button] ---> pageA --- [user click] ---> pageB

The result if that sometimes the scrollTop value of pageB is not 0

On the transition itself, there are some page height changes, required for the animation that makes. Probably Chrome redraws the page and recalculates scrollTop based on some internal value, but hard to tell whether there's a bug in Chrome itself 

I tried two different packages for applying transitions (jamielob:transitions and ccorcos:transitioner), so not that likely there's a bug in the animation itself

So I am now shifting to a sort of workaround mode, where I could get the scrollTop value before the transition (but after it's being set by scroll plugin) and set it again after the transition

**Comment by ghost** [comment]
Hello @mrgiba , at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
