### ISSUE TITLE
Force it to every route?

### ISSUE THREAD

**Issue by dnish** [okgrow/router-autoscroll#38]
Hi,
is it possible to force the last scrolling position to every route? At the moment I need to add #maintainScroll hash to every url to make it work.

**Comment by karldanninger** [comment]
Hey! I'm confused, could you please clarify? What is the behaviour you are trying to achieve?

If #maintainScroll was added on every route, then that would defeat the purpose of this package

**Comment by dnish** [comment]
@kdanninger The examples aren't working on my devices (iPhone and Mac, Safari and Chrome). It only works if I explicit add the "#maintainScroll" hash to every link. When I install <code>tomwasd:flow-router-autoscroll</code> everything works fine, even without the hash.

**Comment by karldanninger** [comment]
Weird, the example apps are working for me.

What exactly is _not_ working?

**Comment by dnish** [comment]
If I click on a link and then go back, I'm back at the top of the page and not at the last position where I've leaved the route.

**Comment by ghost** [comment]
Hello @dnish, at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
