### ISSUE TITLE
Package not working with Chrome out of the box

### ISSUE THREAD

**Issue by acomito** [okgrow/router-autoscroll#39]
Any idea why this isn't working out of the box?

packages:

```
reactive-var
aldeed:collection2
erasaur:meteor-lodash
meteortoys:allthings
momentjs:moment
email
fastclick
gwendall:auth-client-callbacks
check
http
force-ssl
raix:handlebar-helpers
aldeed:template-extension
easy:search
easysearch:components
natestrauser:animate-css
less
matb33:bootstrap-glyphicons
fortawesome:fontawesome
dapearce:material-icons
jonperl:accounts-linkedin
accounts-ui
accounts-password
service-configuration
bozhao:link-accounts
useraccounts:core
useraccounts:unstyled
useraccounts:flow-routing
accounts-google
ejson
lukemadera:autoform-googleplace
dburles:google-maps
aldeed:autoform
cloudspider:autoform-tags-typeahead
mayankchhabra:autoform-switchery
useful:wizard
vazco:universe-autoform-select
cosio55:autoform-cloudinary
aramk:rangeslider
robertlowe:autoform-pickadate
 mpowaga:autoform-summernote
 jeremy:selectize
 comerc:autoform-selectize
 chhib:selectize-bootstrap-3
juliancwirko:s-alert
juliancwirko:s-alert-jelly
kevohagan:sweetalert
webdeb:app-loader
lookback:dropdowns
dsyko:hopscotch
lookback:tooltips
matdutour:popup-confirm
kadira:flow-router
kadira:blaze-layout
zimme:active-route
meteorhacks:ssr
okgrow:router-autoscroll
aldeed:tabular
meteorhacks:kadira
okgrow:analytics

```

**Comment by acomito** [comment]
UPDATE:

It seems this issue is only in chrome. any ideas on how to fix it?

**Comment by pauldowman** [comment]
It works for me in Chrome using the [flow router demo app](https://github.com/okgrow/router-autoscroll/tree/master/examples/flow-router-example). Can you try that? If that works but your app doesn't we'll need you to narrow down what's causing the issue. (Unfortunately you'll need to use the example app locally since the hosted version went down with all of the meteor.com free sites, I'll open a separate issue to host those somewhere else).

**Comment by Rahbaran** [comment]
Hi there,
I have the same issue with: only not working in Chrome, I'm using Iron Router. 
You can check it out here here (un: uzh, pw: osn):  [Open Strategy Network](http://openstrategynetwork.com). It even works in Safari ;)

**Comment by vmatekole** [comment]
@acomito and @Rahbaran - In my case this issue was caused by having 100% height on the body/html. Removing this resolved the problem.

**Comment by Rahbaran** [comment]
@vmatekole thx, I'll check it out :)
