### ISSUE TITLE
Where to put RouterAutoscroll.animationDuration = (myValue); ?

### ISSUE THREAD

**Issue by deborah-ufw** [okgrow/router-autoscroll#42]
Hello. Where does this go? In routes.js? Or where? 

If in routes.js, can you provide an example?

Thank you for creating this plugin!!

**Comment by WitaliB** [comment]
I think you can put it anywhere on the client js with:
`RouterAutoscroll.animationDuration = 100;`

If you put in somewher like "both" you would use:

```
if(Meteor.isClient){
  RouterAutoscroll.animationDuration = 100;
}
```

**Comment by ghost** [comment]
@deborah-ufw Looks like Paul answered this question for us, I'll close this issue for now.
