### ISSUE TITLE
Question: Is there a function to scroll to top?

### ISSUE THREAD

**Issue by WitaliB** [okgrow/router-autoscroll#43]
is there something like
`RouterAutoscroll.scrollTo(0);`

Now I am using
`$('body,html').animate({ scrollTop: 0 }, RouterAutoscroll.animationDuration);`

thanks

**Comment by ghost** [comment]
Hello @paul-bo, at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
