### ISSUE TITLE
FlowRouter.setQueryParams({...}) and 'maintainScroll=1'

### ISSUE THREAD

**Issue by WitaliB** [okgrow/router-autoscroll#45]
When I set a query param for pagination how to prevent scrolling to the top with:
`'maintainScroll=1'`

my code:
`FlowRouter.setQueryParams({ limit: newLimit });`

**Comment by ghost** [comment]
Hello @paul-bo , at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
