### ISSUE TITLE
Transition to npm?

### ISSUE THREAD

**Issue by nickredmark** [okgrow/router-autoscroll#46]
Are there any plans to transition this package to npm?

**Comment by cfnelson** [comment]
@nmaro We will be assessing all our packages this Friday to determine which packages we plan to migrate to NPM & continue supporting. I will let you know what we end up deciding.

**Comment by ghost** [comment]
Hello @nmaro, unfortunately, we will not be continuing any development of router-autoscroll. At OK GROW we are using react-router which will include auto scroll functionality, this package will be deprecated as of now.

**Comment by nickredmark** [comment]
Thanks for coming back to me
