### ISSUE TITLE
Scroll doesn't trigger if route is not ready()

### ISSUE THREAD

**Issue by deanrad** [okgrow/router-autoscroll#5]
_From @deanius on August 25, 2015 15:30_

The version of ready() depended upon in this package is not reactive, and if it returns false, the scrollToTop logic we care about does not run.

This, and other timing fixes like #17 could be worked on together in a single patch:
- if the route is not ready:
  - if the scroll position will be to the top, it's ok (top position will not change w.r.t. length of content)
  - change the scroll position after the route is ready
    - but not if the user has started scrolling

_Copied from original issue: okgrow/iron-router-autoscroll#18_

**Comment by deanrad** [comment]
In the absence of a reproduction case, this will be closed as unactionable.

**Comment by thomasspiesser** [comment]
hey, 
I found that whenever data is loading, scrolltop is not triggered, meaning that when the data is there and the template changed/filled, the scroll position is somewhere in the middle of the page (observe here: https://traincrowd.de/ ). is that issue related? btw using iron:router

**Comment by krishaamer** [comment]
Also having this problem. Any solution yet?

**Comment by RemyLespagnol** [comment]
+1

**Comment by catin-black** [comment]
+1

**Comment by ghost** [comment]
Hello all, at OK GROW we no longer use this package in our projects. We will no longer be dedicating the resources to maintaining this package. If you would like to support this package, feel free to fork it.
