### ISSUE TITLE
Scroll triggers late

### ISSUE THREAD

**Issue by deanrad** [okgrow/router-autoscroll#6]
_From @SachaG on August 5, 2015 5:11_

I've noticed that on some occasions, the scroll triggers a few moments too late, which means the user has already started scrolling down the page and is forcibly brought back to the top. 

Maybe the package could listen for the scroll event, and not trigger if the user has already started scrolling?

_Copied from original issue: okgrow/iron-router-autoscroll#17_

**Comment by deanrad** [comment]
_From @pauldowman on August 5, 2015 12:15_

Great suggestion, we should definitely do that. I'll try to find time for it soon.

**Comment by ghost** [comment]
@deanius similar response to your previous issue. In short, we will no longer be supporting this package as we now use react-router which will have this functionality built in. Feel free to fork it and support it for yourself!
